"""v2_reliability_5_tables

Revision ID: 09484d8d5eb7
Revises: 0002_search_profiles
Create Date: 2026-04-26 19:13:53.317198+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '09484d8d5eb7'
down_revision: Union[str, None] = '0002_search_profiles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_index('ix_activity_log_source_ts', 'activity_log', ['source', 'ts'], unique=False)
    op.create_index('ix_activity_log_ts', 'activity_log', ['ts'], unique=False)
    op.create_table('health_checks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_checks'))
    )
    op.create_index('ix_health_checks_scenario_ts', 'health_checks', ['scenario', 'ts'], unique=False)
    op.create_table('messenger_chats',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('contact_id', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('is_my_listing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messenger_chats'))
    )
    op.create_index('ix_messenger_chats_last_message_at', 'messenger_chats', ['last_message_at'], unique=False)
    op.create_table('chat_dialog_state',
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('bot_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_reply_message_id', sa.Text(), nullable=True),
    sa.Column('last_qualified_lead_score', sa.Integer(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['messenger_chats.id'], name=op.f('fk_chat_dialog_state_channel_id_messenger_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', name=op.f('pk_chat_dialog_state'))
    )
    op.create_table('messenger_messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['messenger_chats.id'], name=op.f('fk_messenger_messages_channel_id_messenger_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messenger_messages'))
    )
    op.create_index('ix_messenger_messages_channel_created', 'messenger_messages', ['channel_id', 'created_at'], unique=False)
    # NOTE: autogenerate also flagged a spurious diff on listings.avito_id (drop unique
    # constraint + change index unique=False -> unique=True). That stems from the model
    # using `unique=True, index=True` on the column while migration 0002 created a
    # separate UniqueConstraint + non-unique index. Existing schema is functionally
    # equivalent; per V2 Stage 2 constraints we MUST NOT touch existing tables, so the
    # diff is intentionally omitted here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messenger_messages_channel_created', table_name='messenger_messages')
    op.drop_table('messenger_messages')
    op.drop_table('chat_dialog_state')
    op.drop_index('ix_messenger_chats_last_message_at', table_name='messenger_chats')
    op.drop_table('messenger_chats')
    op.drop_index('ix_health_checks_scenario_ts', table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index('ix_activity_log_ts', table_name='activity_log')
    op.drop_index('ix_activity_log_source_ts', table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
